/**
 * 🛠️ THE ULTIMATE CP TEMPLATE BLUEPRINT: LAGRANGE INTERPOLATION O(K)
 *
 * 1. 🎯 WHAT PROBLEM DOES THIS SOLVE?
 * - Keywords: "N-th term of a sequence", "Sum of i^p", "Polynomial fitting".
 * - Classic Scenarios: You know a sequence is generated by a polynomial of degree K.
 *   You need the exact value at a massive index X (e.g., X = 10^18), but you can
 *   only easily compute the first K+1 values (at x = 0, 1, 2, ..., K).
 * - The Magic: Standard Lagrange takes O(K^2). Because our evaluation points are
 *   strictly contiguous integers (0 to K), the products in the numerator and
 *   denominator become factorials and prefix/suffix products. This collapses the
 *   complexity to pure O(K), allowing you to evaluate degree 10^6 polynomials in
 *   less than a second.
 *
 * 2. 📦 HOW TO USE IT (THE BLACK BOX)
 * - Query:
 *       long long ans = lagrange_eval(Y, X);
 *       // Y is a vector of size K+1 containing P(0), P(1), ..., P(K).
 *       // X is the massive point you want to evaluate at.
 *
 * - Complexity:
 *       Time: O(K) where K is the degree of the polynomial (size of Y - 1).
 *       Space: O(K) for prefix/suffix and factorial arrays.
 *
 * 3. ⚙️ HOW TO ADAPT IT (THE DIALS & SWITCHES)
 * - Modulo: Adjust the global MOD variable if the problem uses 1e9+7 instead
 *   of 998244353.
 */

using ll = long long;
const ll MOD = 998244353;

ll binpow(ll base, ll exp)
{
    ll res = 1;
    base %= MOD;
    while (exp > 0)
    {
        if (exp % 2 == 1)
            res = (res * base) % MOD;
        base = (base * base) % MOD;
        exp /= 2;
    }
    return res;
}

ll modInverse(ll n)
{
    return binpow(n, MOD - 2);
}

ll lagrange_eval(const vector<ll> &y, ll x)
{
    int k = y.size() - 1;
    if (x <= k)
        return y[x];

    vector<ll> pref(k + 1, 1), suff(k + 1, 1);
    vector<ll> fact(k + 1, 1), invFact(k + 1, 1);

    for (int i = 1; i <= k; i++)
        fact[i] = fact[i - 1] * i % MOD;
    invFact[k] = modInverse(fact[k]);
    for (int i = k - 1; i >= 0; i--)
        invFact[i] = invFact[i + 1] * (i + 1) % MOD;

    pref[0] = x % MOD;
    for (int i = 1; i <= k; i++)
        pref[i] = pref[i - 1] * (x - i) % MOD;

    suff[k] = (x - k) % MOD;
    for (int i = k - 1; i >= 0; i--)
        suff[i] = suff[i + 1] * (x - i) % MOD;

    ll ans = 0;
    for (int i = 0; i <= k; i++)
    {
        ll num = (i == 0 ? 1 : pref[i - 1]) * (i == k ? 1 : suff[i + 1]) % MOD;
        ll den = invFact[i] * invFact[k - i] % MOD;
        ll term = y[i] * num % MOD * den % MOD;
        if ((k - i) % 2 == 1)
        {
            ans = (ans - term + MOD) % MOD;
        }
        else
        {
            ans = (ans + term) % MOD;
        }
    }
    return ans;
}